# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
import numpy as np  
zeros_array =np . zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [4]:
import numpy as np
ones_array = np . ones(10)

#### Create an array of 10 fives

In [5]:
import numpy as np
fives_array = (10,50)

#### Create an array of the integers from 10 to 50

In [6]:
import numpy as np
array = np. arange(10,51)

#### Create an array of all the even integers from 10 to 50

In [7]:
import numpy as np
even_array = np . arange(10,51,2)

#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
import numpy as np
matrix =np . arange(9).reshape(3,3)

#### Create a 3x3 identity matrix

In [9]:
import numpy as np
identity_matrix = np . eye(3)

#### Use NumPy to generate a random number between 0 and 1

In [11]:
import numpy as np
random_number = np . random .rand()

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [12]:
import numpy as np 
random_array = np . random . randn(25)

#### Create the following matrix:

In [13]:
import numpy as np
matrix = np . arange(0.01 , 0.31 , 0.01).reshape(3,10)

#### Create an array of 20 linearly spaced points between 0 and 1:

In [14]:
import numpy as np
linear_array = np .linspace(0,1,20)

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [15]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [19]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [20]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [18]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!